#! /bin/sh

DIR="$(cd "$(dirname "$0")"; pwd)"

IMG=$(docker build -q $DIR/.workbench)

if [ "$#" -eq 0 ]; then
    CMD="bash"
    WB_MODE="-it"
else
    CMD="$@"
    WB_MODE=""
fi

docker run --rm \
    -v /etc/passwd:/etc/passwd \
    -v /etc/group:/etc/group \
    -v $HOME:$HOME \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $WB_MODE $IMG sudo -u ${USER} -E sh -c "cd $DIR; $CMD"
